[mysqld]
datadir=d:/工作/code/spiderV5_optimized/setup/mariadb-10.11.18-winx64/data
basedir=d:/工作/code/spiderV5_optimized/setup/mariadb-10.11.18-winx64
port=3306
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
innodb_buffer_pool_size=512M
max_connections=100

[mysql]
default-character-set=utf8mb4
